name: Anubis Server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  anubis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build Anubis
        run: |
          cd anubis
          npm ci
          npm run assets
          go build -o ./var/anubis ./cmd/anubis

      - name: Start Anubis
        run: |
          cd anubis
          chmod +x ./var/anubis
          BIND=127.0.0.1:8923 \
          TARGET=https://hastagaming.github.io/service-hub/ \
          TARGET_HOST=hastagaming.github.io \
          TARGET_SNI=hastagaming.github.io \
          USE_REMOTE_ADDRESS=true \
          ./var/anubis